---
- hosts: all
  tasks:
    - name: 显示当前系统版本
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }} {{ ansible_distribution_major_version }} {{ ansible_os_family }} {{ ansible_pkg_mgr }} {{ ansible_service_mgr }} {{ ansible_user_id }} {{ ansible_user_uid }} {{ ansible_user_gid }} {{ ansible_user_dir }} {{ ansible_architecture }}"